apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  volumes:
    - name: cache-volume
      emptyDir: {}
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "echo 'K8s é legal' > /cache/arquivo.txt && sleep 3600"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
    - name: reader
      image: busybox
      command: ["sh", "-c", "sleep 5 && cat /cache/arquivo.txt && sleep 3600"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
