apiVersion: v1
kind: Pod
metadata:
  name: my-hostpath-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    persistentVolumeClaim:
      claimName: my-hostpath-pvc
