apiVersion: v1
kind: Deployment
metadata:
  name: volume
spec:
  template:
    metadata:
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: logs
           # Criar este diretório com mkdir antes
           # mkdir /home/ambientelivre/hacks/k8s/volumes/disk_redis -p
          mountPath: /home/ambientelivre/k8s/volumes/disk_redis 
