apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ambientelivre-csr
spec:
  groups:
  - system:authenticated
  request: <atribuir valor codificado a partir do próximo comando cat>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
